INSERT INTO posts (title, description, content) VALUES ('Post 1', 'Post 1 Description', 'Post 1 Content')
INSERT INTO posts (title, description, content) VALUES ('Post 2', 'Post 2 Description', 'Post 2 Content')
INSERT INTO posts (title, description, content) VALUES ('Post 3', 'Post 3 Description', 'Post 3 Content')
INSERT INTO posts (title, description, content) VALUES ('Post 4', 'Post 4 Description', 'Post 4 Content')
INSERT INTO posts (title, description, content) VALUES ('Post 5', 'Post 5 Description', 'Post 5 Content')
INSERT INTO posts (title, description, content) VALUES ('Post 6', 'Post 6 Description', 'Post 6 Content')
INSERT INTO posts (title, description, content) VALUES ('Post 7', 'Post 7 Description', 'Post 7 Content')
INSERT INTO posts (title, description, content) VALUES ('Post 8', 'Post 8 Description', 'Post 8 Content')
INSERT INTO posts (title, description, content) VALUES ('Post 9', 'Post 9 Description', 'Post 9 Content')
INSERT INTO posts (title, description, content) VALUES ('Post 10', 'Post 10 Description', 'Post 10 Content')
INSERT INTO posts (title, description, content) VALUES ('Post 11', 'Post 11 Description', 'Post 11 Content')
INSERT INTO posts (title, description, content) VALUES ('Post 12', 'Post 12 Description', 'Post 12 Content')
INSERT INTO posts (title, description, content) VALUES ('Post 13', 'Post 13 Description', 'Post 13 Content')
INSERT INTO posts (title, description, content) VALUES ('Post 14', 'Post 14 Description', 'Post 14 Content')
INSERT INTO posts (title, description, content) VALUES ('Post 15', 'Post 15 Description', 'Post 15 Content')

INSERT INTO users (email, username, name, password) VALUES('gustavo@gmail.com', 'ggavanch', 'Gustavo', '$2a$10$QESJRAOldMYekuXxbM5IkOO1n9beEjiIzatNVMDKaNhFAuE7XuzMi')
INSERT INTO users (email, username, name, password) VALUES('admin@admin.com', 'admin', 'Admin', '$2a$10$UwJVAdS/gr0P99iC8GDQ7O/Okk8Dd5aD6kmol8zyf3XYnK1GS1jeS')

INSERT INTO roles (name) VALUES ('ROLE_USER')
INSERT INTO roles (name) VALUES('ROLE_ADMIN')

INSERT INTO users_roles (user_id, role_id) VALUES(1,  1)
INSERT INTO users_roles (user_id, role_id) VALUES(2,  2)